# Definições de SO
dist: xenial
os: linux

# Linguagem Utilizada para Desenvolver a Aplicação                                                                                                                                                       
language: python                                                                                                                                                                                         

# Versão que a aplicação suporta.                                                                                                                                                                        
python:                                                                                                                                                                                                  
  - "3.7.9"                                                                                                                                                                                              

jobs:
  include:

    # Teste pytest
    - stage: Teste
      name: "Testes Unitarios"
      # Instalação de Módulos que são necessários para a Aplicação.
      install:
        - pip install flask flask-wtf coverage
      script:  # Defini o script de Teste que deve rodar toda vez que o código for alterado.
        - coverage run test.py || travis_terminate 1;
        - coverage report app.py || travis_terminate 1;
        - coverage xml app.py || travis_terminate 1;
      workspaces:
        create:
          name: "coverage"
          paths:
            - coverage.xml

    # Teste Sonar
    - stage: Teste
      name: "Testes de Qualidade e Seguranca"
      script:
        - sonar-scanner || travis_terminate 1;
      workspaces:
        use: "coverage"
      addons:
        sonarcloud:
          organization: santospedroh
          token: ${SONAR_TOKEN}

    # Definir o STG Deploy no Heroku
    - stage: Stage Deploy
      script: skip      
      deploy:
        provider: heroku
        api_key:
          secure: pN216dhnAaiXhCDoXI0SVuuaaF5U3BDi4rJqQkNyP2uc5UGk1Bmks+hn5eYMlywKi7sl38y6EktMelwmt0QffIgsbWntXo2qvtrtpknYtRuXnp5XyqscwBfwZtSccV8mt72ltUOLSYm3whjarlqDi0xHLK/bRDG8D3EZj9XGTJmqBl/67WdPVLckON3M30KONemvfJ51jWh/L///niRw5NNeCfFk8ZQE8ZS2QKYYnIdBlnBj/Zha9cy7Nk5zcI10NnvYHNzgLfKM+vgHFvHSI8AobB5S09ntXG2KK4s3A12/Ma/hnOCp9U4cT7gOU21vM6/7OsEs9Q71UH17N2AtGAplFq5FNBUWkiZ+PNGJ69Hro3mE9eWm/5VtnfCn51iq6GjvIMGiVneD4ptB/hLAGDexMpNbnRPb2qBWBetJ6VyCa+LKv4NyQ8dgXQd+H20teEutW5BM42cvFaZDNVxKXExK690YCm9II2Hxt61L2tbzdr/Quy40ykrG9d5F62ezzsaVrIcT+Er/xzExYeFPBQ9Y/dQ/Cqkzcfvb6Rz8j7JQWnRJwy2+a86eJxiBA73fVstWCwVFdKfW2mmFFIb4zdhni17QE+yHxbmWP2ncMRp2u+bHqDb1867pN8N3qzRiPGTAjrWEkJHtNJscKB1mjn/WK936howUuuAQkC5wjkk=
        app: devopslab-pedro-stg
        on:
          branch: main

    # Definir o PROD Deploy no Heroku
    - stage: Production Deploy
      script: skip      
      deploy:
        provider: heroku
        strategy: api
        api_key:
          secure: pN216dhnAaiXhCDoXI0SVuuaaF5U3BDi4rJqQkNyP2uc5UGk1Bmks+hn5eYMlywKi7sl38y6EktMelwmt0QffIgsbWntXo2qvtrtpknYtRuXnp5XyqscwBfwZtSccV8mt72ltUOLSYm3whjarlqDi0xHLK/bRDG8D3EZj9XGTJmqBl/67WdPVLckON3M30KONemvfJ51jWh/L///niRw5NNeCfFk8ZQE8ZS2QKYYnIdBlnBj/Zha9cy7Nk5zcI10NnvYHNzgLfKM+vgHFvHSI8AobB5S09ntXG2KK4s3A12/Ma/hnOCp9U4cT7gOU21vM6/7OsEs9Q71UH17N2AtGAplFq5FNBUWkiZ+PNGJ69Hro3mE9eWm/5VtnfCn51iq6GjvIMGiVneD4ptB/hLAGDexMpNbnRPb2qBWBetJ6VyCa+LKv4NyQ8dgXQd+H20teEutW5BM42cvFaZDNVxKXExK690YCm9II2Hxt61L2tbzdr/Quy40ykrG9d5F62ezzsaVrIcT+Er/xzExYeFPBQ9Y/dQ/Cqkzcfvb6Rz8j7JQWnRJwy2+a86eJxiBA73fVstWCwVFdKfW2mmFFIb4zdhni17QE+yHxbmWP2ncMRp2u+bHqDb1867pN8N3qzRiPGTAjrWEkJHtNJscKB1mjn/WK936howUuuAQkC5wjkk=
        app: devopslab-pedro
        on:
          branch: main

# Travis Slack
notifications:
  slack:
    secure: BJJ8jgUyYoFxgzhhaTalSaTMSnWsR/H+o4yB5agHpSy9l3Dzk9bTunt37iuRRog/u8XgFbW+Kmwfcr3UD0tZ3yzRDzGrVJSdtAMn/oDggxiofNdtWi5JNbuLQcrpsD1r+pkAwTyX/S6j22KRSjAZeLlcAkQ9ws9xEAJXftk+NqCUVjZegMzQbPlhs67gW/HqI5kCeuuJaR1VjyVaEIZD3OZ4CS7odmK4HHTKzFsWFmWYt8YJ07wXsg8r3gvlDjj4SUhlyoU9CrUwmZi/rAwzGIMgjskvWohU2zfk9W+pDb4H7RXS2sZsIxEauGQ4u0kEaeAdgQUhxGVKAxLfavPsflcmIshj2FZOQJIjnR0VnZgwhhmwo49c3x+gpXEdw6wkhD81/4g0UnRNGC+sNqmnqx4jDfUMZOOAUZBHHj94YLgzCuDw0tRcjQULgOVVH2BnWh+mGRpDOyaj7909LcaiAafqBUdrjrvEvt6kfR7apfEIzKO+h/8LJOypIOTlk/jSEd3rvTNbRPXqZ+0KkEF6o2DM0OnRFZii1bb1s9QjjCOsmBS3p57BTZhUqoyOz9cgIQKfaOg3x2DL116iBYWLrfCNE24B+NrNDBGbN3e/PADv8y1NcgEYFiHYCPLKqJsoHRiYqyZXo5dQr6qsIDw55tsVwYyup+1tN38pc4KXdQ0=
    on_success: always
    on_failure: always
